sudo: required
services:
  - docker

before_install:
  - docker build -t geophray/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run geophray/react-test npm test -- --coverage

after_success:
  - docker build -t geophray/multi-client ./client
  - docker build -t geophray/multi-nginx ./nginx
  - docker build -t geophray/multi-server ./server
  - docker build -t geophray/multi-worker ./worker
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push geophray/multi-client
  - docker push geophray/multi-nginx
  - docker push geophray/multi-server
  - docker push geophray/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-411555665233
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY